### PR TITLE
create runner package to separate concerns

### PR DESCRIPTION
**Pull request by jmrodri**
The idea here is that bundle.go should only deal with CLI aspects:
parameter parsing, printing help, etc.

### CODE REVIEW

**Comment by jmrodri** [comment]
Fixes #18

**Comment by jmrodri** [comment]
I wanted to base my setup_namespace changes on this PR.

**Comment by jmrodri** [comment]
I was able to provision postgresql using this branch.

```
[jesusr@speed3 sbcli{addrunner}]$ ./sbcli bundle provision postgresql-apb -p zeusville                                                 
List of available plans:                                                                                                               
name: dev                                                                                                                              
name: prod                                                                                                                             
Enter name of plan you'd like to deploy: dev                                                                                           
Plan: dev                                                                                                                              
Enter value for parameter [postgresql_database], default: [admin]:                                                                     
Enter value for parameter [postgresql_user], default: [admin]:                                                                         
Enter value for parameter [postgresql_password], default: []: passwod                                                                  
Enter value for parameter [postgresql_version], default: [9.6]:                                                                        
WARN Failed to create a InternalClientSet: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT
must be defined.                                                                                                                       
Successfully created pod [bundle-bf0c0703-43c3-4808-986f-71e4f3feed0d] to provision [postgresql-apb] in namespace [zeusville]          
```

```
[jesusr@speed3 sbcli{addrunner}]$ oc get pods
NAME                                          READY     STATUS      RESTARTS   AGE 
bundle-bf0c0703-43c3-4808-986f-71e4f3feed0d   0/1       Completed   0          4m  
postgresql-9.6-dev-1-2lhz8                    1/1       Running     0          4m  
```

**Comment by djwhatle** [comment]
+1, felt like bundle.go was getting a bit bloated.

**Pull request merged**
